package com.hydroyura.eta.chatbot.domain.statemachine;

public enum State {
    INITIAL,
    AWAITING_REGISTRATION_NAME,
    ACTIVE,
    AWAITING_STUDENT_NAME,
    STUDENTS_LIST,
    STUDENT_OPTIONS,
    STUDENT_DETAILS,
    IN_LESSON,
    AWAITING_WORD,
    AWAITING_POS,
    AWAITING_TRANSLATION,
    AWAITING_EXERCISE_TYPE,
    AWAITING_EXERCISE_TOPIC,
    AWAITING_EXERCISE_ANSWER
}
